[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dominosim"
version = "0.1.0"
description = "Python level editing library for Kyowob's Domino Simulator"
authors = [{ name="qaptivator" }]
dependencies = []
#requires-python = ">=3.7"